version: '3'

services:
  streamlit:
    build: .
    ports:
      - '8484:8484'
    container_name: streamlit-twilio-manager
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.st-twilio-manager.entrypoints=http
      - 'traefik.http.routers.st-twilio-manager.rule=Host(`solutions.dataunboxed.io`) && PathPrefix(`/twilio`)'
      - traefik.http.routers.st-twilio-manager.middlewares=redirect-to-https
      - traefik.http.routers.st-twilio-manager-secure.entrypoints=https
      - 'traefik.http.routers.st-twilio-manager-secure.rule=Host(`solutions.dataunboxed.io`) && PathPrefix(`/twilio`)'
      - traefik.http.routers.st-twilio-manager-secure.tls=true
      - traefik.http.routers.st-twilio-manager-secure.tls.certresolver=letsencrypt
      - traefik.http.middlewares.strip-twilio-prefix.stripprefix.prefixes=/twilio
      - traefik.http.routers.st-twilio-manager-secure.middlewares=strip-twilio-prefix
      - traefik.http.services.st-twilio-manager.loadbalancer.server.port=8484
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    networks:
      - coolify
networks:
  coolify:
    external: true
