services:
  streamlit:
    build: .
    ports:
      - '8484:8484'
    container_name: streamlit-twilio-manager
    restart: unless-stopped
    networks:
      - coolify
networks:
  coolify:
    external: true
