version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8484:8484"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1 
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_BASE_URL_PATH=/twilio-manager/
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8484
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit.rule=PathPrefix(`/twilio-manager/`)"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8484"
      - "traefik.http.middlewares.streamlit-strip.stripprefix.prefixes=/twilio-manager"
      - "traefik.http.routers.streamlit.middlewares=streamlit-strip"
