[project]
name = "twilio-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.0.1",
    "twilio>=9.4.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
