# name: Deploy to Coolify

# on:
#   push:
#     branches: [ main, master ]
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Coolify Deployment
#         run: |
#           curl -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }} \
#             -H "Content-Type: application/json" 